### ISSUE TITLE
Usage in Docker

### ISSUE THREAD

**Issue by eikaramba** [Maxime-J/umami-sqlite#2]
This is more a question than an issue. I wanted to use the base image from umami and just add some docker lines to patch it
e.g.
```
FROM ghcr.io/umami-software/umami:postgresql-latest AS base
ADD https://raw.githubusercontent.com/Maxime-J/umami-sqlite/main/1.40.0.patch /app
WORKDIR /app
USER root
RUN chmod +x /app/1.40.0.patch
RUN patch -p1 < /app/1.40.0.patch
```

but of course that does not work. the patch needs to be applied before building. so currently i am creating my own docker container from scratch, basically using the dockerfile from umami as a base and just adding the patch somewhere.

i am just curious (not an docker expert). could i just git clone the whole repo within a dockerfile to avoid having to maintain my own repo with the source files in it? again, this is just a question and if you don't have the time or knowledge feel free to ignore this and close the ticket. no hard feelings :)

**Comment by Maxime-J** [comment]
Indeed, going from scratch is the better way to go :)

I'm not very familiar with Docker, but yes, what you suggest is feasible.
Basing on the Dockerfile from umami, it can be done with something like that:
```
FROM node:16-alpine AS umami
RUN apk add --no-cache git
RUN git clone https://github.com/umami-software/umami

FROM node:16-alpine AS deps
RUN apk add --no-cache libc6-compat
WORKDIR /app
COPY --from=umami /umami/package.json ./
COPY --from=umami /umami/yarn.lock ./
RUN yarn install --frozen-lockfile

FROM node:16-alpine AS builder
COPY --from=umami /umami /app
COPY --from=deps /app/node_modules /app/node_modules
WORKDIR /app

[...]
```

**Comment by eikaramba** [comment]
thank you, i am now trying to use my own repo for now. on windows because of the EOL syntax it is a little bit more difficult to apply the patch. but i will make it work for sure.

and if that does not work, i will just clone inside a docker container ;)

**Comment by eikaramba** [comment]
unfortunately i need to reopen this ticket: i get
```
2023-03-30T15:48:54.797689683Z $ npm-run-all check-db update-tracker start-server
2023-03-30T15:48:55.695429938Z $ node scripts/check-db.js
2023-03-30T15:48:55.945922750Z ✓ DATABASE_URL is defined.
2023-03-30T15:48:56.060971261Z ✗ Unable to connect to the database.
```

i patched the source files. i have a hard time understanding what the problem is

volume is on /database
database_url is file:/database/db.db
indeed i cannot see a database file inside the volume i just don't know why

**Comment by eikaramba** [comment]
could it be that the prisma folder needs to be a persistant volume? because i tried to build locally and saw that upon building a database file is created int he prisma folder!
that could explain why just setting an abritrary path does not work

**Comment by Maxime-J** [comment]
Weird, a database connection error in that context likely means Prisma can't access the path you gave.

About your last message, if not already there the db file is created when `check-db` is run, knowing that:
-for a relative path, in most situations, it's relative to the prisma folder.
-with the way Umami is handling Docker, `check-db` isn't called during build process, but at start.
```
"build": "npm-run-all build-db check-db build-tracker build-geo build-app",
"build-docker": "npm-run-all build-db build-tracker build-geo build-app",
"start-docker": "npm-run-all check-db update-tracker start-server",
"check-db": "node scripts/check-db.js",
```

So, if you gave it /database/db.db, with docker volume mounted on /database,
no db file is created in prisma folder, no db file is created during build process, db.db should be created at container first run in your docker volume.

Would you mind to share the Dockerfile and the command used to run the container?

**Comment by eikaramba** [comment]
here is the dockerfile

```
# Install dependencies only when needed
FROM node:16-alpine AS deps
# Check https://github.com/nodejs/docker-node/tree/b4117f9333da4138b03a546ec926ef50a31506c3#nodealpine to understand why libc6-compat might be needed.
RUN apk add --no-cache libc6-compat
WORKDIR /app
COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile

# Rebuild the source code only when needed
FROM node:16-alpine AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .

ARG BASE_PATH

ENV BASE_PATH $BASE_PATH
ENV DATABASE_URL=file:./database.db

ENV NEXT_TELEMETRY_DISABLED 1


# RUN apk add patch
# RUN chmod +x /app/sqlite.patch
# RUN patch -p1 < /app/sqlite.patch


RUN yarn build-docker

# Production image, copy all the files and run next
FROM node:16-alpine AS runner
WORKDIR /app


# RUN mkdir -p /database
VOLUME /app/prisma

ENV NODE_ENV production
ENV NEXT_TELEMETRY_DISABLED 1

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

RUN yarn add npm-run-all dotenv prisma

# You only need to copy next.config.js if you are NOT using the default configuration
COPY --from=builder /app/next.config.js .
COPY --from=builder --chown=nextjs:nodejs /app/public ./public
COPY --from=builder /app/package.json ./package.json
COPY --from=builder /app/prisma ./prisma
COPY --from=builder /app/scripts ./scripts

# Automatically leverage output traces to reduce image size
# https://nextjs.org/docs/advanced-features/output-file-tracing
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

USER nextjs


EXPOSE 3000

ENV PORT 3000

CMD ["yarn", "start-docker"]
```

as you see i set the folder to the prism local folder. i now can also see this in the docker volume, so the volume works but indeed is missing the database file.
![grafik](https://user-images.githubusercontent.com/1320525/228953079-9e30ecbd-6fe4-4deb-8035-9878efe7c182.png)

i also set the ENV variable to the same path, even though i set a default in the dockerfile

**Comment by eikaramba** [comment]
i got it working!

I think it was because the nextjs user does not have rights to write files into the volume. you see at the end of the dockerline, how to this user is switched. normally no problem, but because in the sqlite case we need to write the database this is a problem.

changing it to root fixed it i think. i also changed
ENV DATABASE_URL="file:./database.db" 
to
ENV DATABASE_URL="file:/app/prisma/database.db"
but given that i anyway change the env file in the caprover interface and it overwrites the default it should not matter.

**Comment by Maxime-J** [comment]
Cool!👍 
Thanks for the details.
I'll mention some guidelines in the readme.

I would suggest however to only put the database in the volume, mounting it in a new folder (not the prisma one).
I think it can prevent some future issues in case of updates or whatever.

The previous comment has been deleted in order to leave the implementation to everyone.

**Comment by moookino** [comment]
Hi @Maxime-J 

I'm also trying to adapt Dockerfile to include sqlite, but I'm not sure at which phase I should inject patch, because on the `runner ` phase I see mysql db detected instead in the build log message, which is confusing and I end up getting same problem with unable to connect to db
Can you help me to find what's wrong?


```
2024-07-10 10:55:58 umami-1  | yarn run v1.22.19
2024-07-10 10:55:58 umami-1  | $ npm-run-all check-db update-tracker start-server
2024-07-10 10:55:58 umami-1  | $ node scripts/check-db.js
2024-07-10 10:55:58 umami-1  | ✓ DATABASE_URL is defined.
2024-07-10 10:55:58 umami-1  | ✗ Unable to connect to the database.
2024-07-10 10:55:58 umami-1  | error Command failed with exit code 1.
2024-07-10 10:55:58 umami-1  | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```
docker-compose.yml
```
services:
  umami:
    image: moookino/umami
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: file:/var/lib/postgresql/database.db
      # DATABASE_TYPE: sqlite
      APP_SECRET: replace-me-with-a-random-string
    restart: unless-stopped
    # healthcheck:
    #   test: ["CMD-SHELL", "curl http://localhost:3000/api/heartbeat"]
    #   interval: 5s
    #   timeout: 5s
    #   retries: 5
    volumes:
      - umami-db-data:/var/lib/postgresql/database.db

volumes:
  umami-db-data:
```

Dockerfile
```
FROM arm64v8/node:18-alpine AS deps

RUN apk add git

RUN git clone --depth 1 --single-branch --branch master https://github.com/mikecao/umami.git /app
WORKDIR /app
RUN yarn install --frozen-lockfile

###

FROM arm64v8/node:18-alpine AS builder

RUN apk add git
RUN apk add patch
# This way the pull should not be cached 
ADD "https://www.random.org/cgi-bin/randbyte?nbytes=10&format=h" skipcache
RUN git clone --depth 1 --single-branch --branch master https://github.com/mikecao/umami.git /app
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .
ADD https://raw.githubusercontent.com/Maxime-J/umami-sqlite/main/2.12.1.patch /app
USER root
RUN chmod +x /app/2.12.1.patch
RUN patch -p1 < /app/2.12.1.patch

ENV DATABASE_TYPE mysql
ENV BASE_PATH ''
ENV NEXT_TELEMETRY_DISABLED 1

RUN yarn build-docker

###
# Production image, copy all the files and run next
FROM arm64v8/node:18-alpine AS runner

ENV NODE_ENV production
ENV NEXT_TELEMETRY_DISABLED 1

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

RUN yarn add npm-run-all dotenv prisma
# You only need to copy next.config.js if you are NOT using the default configuration
COPY --from=builder /app/next.config.js .
COPY --from=builder --chown=nextjs:nodejs /app/public ./public
COPY --from=builder /app/package.json ./package.json
COPY --from=builder /app/prisma ./prisma
COPY --from=builder /app/scripts ./scripts

# Automatically leverage output traces to reduce image size
# https://nextjs.org/docs/advanced-features/output-file-tracing
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

USER nextjs

EXPOSE 3000

ENV PORT 3000

CMD ["yarn", "start-docker"]

```
