### ISSUE TITLE
support umami 2.0

### ISSUE THREAD

**Issue by eikaramba** [Maxime-J/umami-sqlite#3]
You will hate me for opening an issue for this (*G*), but no harm in having this tracked here :) Looking forward for having 2.0 support with SQLite. BTW, my instance with umami-sqlite purrs like a cat :)
https://github.com/umami-software/umami/releases/tag/v2.0.0

**Comment by eikaramba** [comment]
in my instance i would be fine to start from scratch and not migrate any data. but i can certainly understand that this is not for everyone. that said, maybe it is not too much work to adapt the migration script? https://github.com/umami-software/migrate-v1-v2/blob/master/db/postgresql/data-migration-v2.sql

**Comment by Maxime-J** [comment]
No problem @eikaramba :), v2 will be supported here very soon (probably next week).
And I will definitely have a look at the migration process 👍

**Comment by Maxime-J** [comment]
Quick update: migration is ok, and SQLite support nearly fully added with some slightly updated methods.

Umami v2 got fixes & changes since its release and there are still some which could be published in a new release soon, so I will wait a few days before finalising it.

**Comment by eikaramba** [comment]
makes sense. i also read that a new version is around the corner and hopefully will already have some improvements of the event system. really hope the event system will be more powerful in the future. maybe even allow some simple funnel analysis.

**Comment by Maxime-J** [comment]
v2 support has just been pushed :) I leave that issue opened a bit in case of issues.
Obviously v2.2.0 is the last one before other big changes, so I'll go with it even if it doesn't include some fixes.

**Comment by eikaramba** [comment]
how did you do the migration? when i do yarn build, the database seems to be deleted and recreated. running npx @umami/migrate-v1-v2@latest however does not detect v1 tables, which are definitely there.

**Comment by Maxime-J** [comment]
Running the official migration script won't work.
Did you see https://github.com/Maxime-J/umami-sqlite/tree/main/migrate-v1-v2 folder ?

The readme there describes how to migrate the database.
Ideally this has to be done from a working 1.40.

But if you're already on patched v2.2.0, you can run `npm run build-db` first,
put back the database saved from 1.40,
download the migrate-v1-v2 folder to Umami's folder, and run from there (Umami's root):
`node migrate-v1-v2/migrate.js`
This should work, but not tested.

**Comment by eikaramba** [comment]
i didn't saw the migration folder sry. thanks for all the work! will try it later

**Comment by Maxime-J** [comment]
Hi, I'll close this issue, v2 is OK for some time now, feel free to open a new issue if needed.
