### ISSUE TITLE
add windows support 

### ISSUE THREAD

**Issue by alphaleadership** [Maxime-J/umami-sqlite#9]

**Comment by Maxime-J** [comment]
Could you be more clear?
Did you try applying the patch?
patch executable from windows git should be able to handle it (with possibly a few line endings warnings, depending on how you got the source files).

**Comment by alphaleadership** [comment]
Ok m'y bad git in Windows have patch command

**Comment by alphaleadership** [comment]
The next patch would create the file migration.sql,
which already exists!  Applying it anyway.
(Stripping trailing CRs from patch; use --binary to disable.)
patching file migration.sql
Hunk #1 FAILED at 1.
1 out of 1 hunk FAILED -- saving rejects to file migration.sql.rej
The next patch would create the file migration.sql,
which already exists!  Applying it anyway.
(Stripping trailing CRs from patch; use --binary to disable.)
patching file migration.sql
Hunk #1 FAILED at 1.
1 out of 1 hunk FAILED -- saving rejects to file migration.sql.rej
The next patch would create the file migration.sql,
which already exists!  Applying it anyway.
(Stripping trailing CRs from patch; use --binary to disable.)
patching file migration.sql
Hunk #1 FAILED at 1.
1 out of 1 hunk FAILED -- saving rejects to file migration.sql.rej
The next patch would create the file migration.sql,
which already exists!  Applying it anyway.
(Stripping trailing CRs from patch; use --binary to disable.)
patching file migration.sql
Hunk #1 FAILED at 1.
1 out of 1 hunk FAILED -- saving rejects to file migration.sql.rej
The next patch would create the file migration.sql,
which already exists!  Applying it anyway.
(Stripping trailing CRs from patch; use --binary to disable.)
patching file migration.sql
Hunk #1 FAILED at 1.
1 out of 1 hunk FAILED -- saving rejects to file migration.sql.rej
The next patch would create the file migration.sql,
which already exists!  Applying it anyway.
(Stripping trailing CRs from patch; use --binary to disable.)
patching file migration.sql
Hunk #1 FAILED at 1.
1 out of 1 hunk FAILED -- saving rejects to file migration.sql.rej
The next patch would create the file migration.sql,
which already exists!  Applying it anyway.
(Stripping trailing CRs from patch; use --binary to disable.)
patching file migration.sql
Hunk #1 FAILED at 1.
1 out of 1 hunk FAILED -- saving rejects to file migration.sql.rej
The next patch would create the file migration.sql,
which already exists!  Applying it anyway.
(Stripping trailing CRs from patch; use --binary to disable.)
patching file migration.sql
Hunk #1 FAILED at 1.
1 out of 1 hunk FAILED -- saving rejects to file migration.sql.rej
The next patch would create the file migration_lock.toml,
which already exists!  Applying it anyway.
(Stripping trailing CRs from patch; use --binary to disable.)
patching file migration_lock.toml
Hunk #1 FAILED at 1.
1 out of 1 hunk FAILED -- saving rejects to file migration_lock.toml.rej
The next patch would create the file schema.prisma,
which already exists!  Applying it anyway.
(Stripping trailing CRs from patch; use --binary to disable.)
patching file schema.prisma
Hunk #1 FAILED at 1.
1 out of 1 hunk FAILED -- saving rejects to file schema.prisma.rej
(Stripping trailing CRs from patch; use --binary to disable.)
can't find file to patch at input line 885
Perhaps you should have used the -p or --strip option?
The text leading up to this was:
--------------------------
|diff --git a/scripts/check-db.js b/scripts/check-db.js
|index cdfeafa3..8ab9345d 100644
|--- a/scripts/check-db.js
|+++ b/scripts/check-db.js
--------------------------
No file to patch.  Skipping patch.
2 out of 2 hunks ignored
(Stripping trailing CRs from patch; use --binary to disable.)
can't find file to patch at input line 951
Perhaps you should have used the -p or --strip option?
The text leading up to this was:
--------------------------
|diff --git a/scripts/copy-db-files.js b/scripts/copy-db-files.js
|index 15c34674..673db6b6 100644
|--- a/scripts/copy-db-files.js
|+++ b/scripts/copy-db-files.js
--------------------------
No file to patch.  Skipping patch.
1 out of 1 hunk ignored
The next patch would create the file sqlite-vacuum.js,
which already exists!  Applying it anyway.
(Stripping trailing CRs from patch; use --binary to disable.)
patching file sqlite-vacuum.js
Hunk #1 FAILED at 1.
1 out of 1 hunk FAILED -- saving rejects to file sqlite-vacuum.js.rej
(Stripping trailing CRs from patch; use --binary to disable.)
can't find file to patch at input line 989
Perhaps you should have used the -p or --strip option?
The text leading up to this was:
--------------------------
|diff --git a/src/lib/db.ts b/src/lib/db.ts
|index 0ffedd0d..6da74a9b 100644
|--- a/src/lib/db.ts
|+++ b/src/lib/db.ts
--------------------------
No file to patch.  Skipping patch.
3 out of 3 hunks ignored
The next patch would create the file prisma-client.ts,
which already exists!  Applying it anyway.
(Stripping trailing CRs from patch; use --binary to disable.)
patching file prisma-client.ts
Hunk #1 FAILED at 1.
1 out of 1 hunk FAILED -- saving rejects to file prisma-client.ts.rej
(Stripping trailing CRs from patch; use --binary to disable.)
can't find file to patch at input line 1140
Perhaps you should have used the -p or --strip option?
The text leading up to this was:
--------------------------
|diff --git a/src/lib/prisma.ts b/src/lib/prisma.ts
|index 32ac65eb..83556028 100644
|--- a/src/lib/prisma.ts
|+++ b/src/lib/prisma.ts
--------------------------
No file to patch.  Skipping patch.
11 out of 11 hunks ignored
(Stripping trailing CRs from patch; use --binary to disable.)
can't find file to patch at input line 1268
Perhaps you should have used the -p or --strip option?
The text leading up to this was:
--------------------------
|diff --git a/src/queries/analytics/events/getWebsiteEvents.ts b/src/queries/analytics/events/getWebsiteEvents.ts
|index 21e6270c..d693e9e6 100644
|--- a/src/queries/analytics/events/getWebsiteEvents.ts
|+++ b/src/queries/analytics/events/getWebsiteEvents.ts
--------------------------
No file to patch.  Skipping patch.
2 out of 2 hunks ignored
(Stripping trailing CRs from patch; use --binary to disable.)
can't find file to patch at input line 1290
Perhaps you should have used the -p or --strip option?
The text leading up to this was:
--------------------------
|diff --git a/src/queries/analytics/events/saveEventData.ts b/src/queries/analytics/events/saveEventData.ts
|index 7e7db8b4..6bf0662a 100644
|--- a/src/queries/analytics/events/saveEventData.ts
|+++ b/src/queries/analytics/events/saveEventData.ts
--------------------------
No file to patch.  Skipping patch.
1 out of 1 hunk ignored
(Stripping trailing CRs from patch; use --binary to disable.)
can't find file to patch at input line 1303
Perhaps you should have used the -p or --strip option?
The text leading up to this was:
--------------------------
|diff --git a/src/queries/analytics/getRealtimeActivity.ts b/src/queries/analytics/getRealtimeActivity.ts
|index fba303b2..2f3446c9 100644
|--- a/src/queries/analytics/getRealtimeActivity.ts
|+++ b/src/queries/analytics/getRealtimeActivity.ts
--------------------------
No file to patch.  Skipping patch.
2 out of 2 hunks ignored
(Stripping trailing CRs from patch; use --binary to disable.)
can't find file to patch at input line 1325
Perhaps you should have used the -p or --strip option?
The text leading up to this was:
--------------------------
|diff --git a/src/queries/analytics/getWebsiteDateRange.ts b/src/queries/analytics/getWebsiteDateRange.ts
|index a4daaafc..f0561267 100644
|--- a/src/queries/analytics/getWebsiteDateRange.ts
|+++ b/src/queries/analytics/getWebsiteDateRange.ts
--------------------------
No file to patch.  Skipping patch.
1 out of 1 hunk ignored
(Stripping trailing CRs from patch; use --binary to disable.)
can't find file to patch at input line 1347
Perhaps you should have used the -p or --strip option?
The text leading up to this was:
--------------------------
|diff --git a/src/queries/analytics/sessions/getSessionActivity.ts b/src/queries/analytics/sessions/getSessionActivity.ts
|index 1fe8bbd3..6c16066a 100644
|--- a/src/queries/analytics/sessions/getSessionActivity.ts
|+++ b/src/queries/analytics/sessions/getSessionActivity.ts
--------------------------
No file to patch.  Skipping patch.
1 out of 1 hunk ignored
(Stripping trailing CRs from patch; use --binary to disable.)
can't find file to patch at input line 1363
Perhaps you should have used the -p or --strip option?
The text leading up to this was:
--------------------------
|diff --git a/src/queries/analytics/sessions/getSessionData.ts b/src/queries/analytics/sessions/getSessionData.ts
|index ce80b035..994e6d8e 100644
|--- a/src/queries/analytics/sessions/getSessionData.ts
|+++ b/src/queries/analytics/sessions/getSessionData.ts
--------------------------
No file to patch.  Skipping patch.
2 out of 2 hunks ignored
(Stripping trailing CRs from patch; use --binary to disable.)
can't find file to patch at input line 1385
Perhaps you should have used the -p or --strip option?
The text leading up to this was:
--------------------------
|diff --git a/src/queries/analytics/sessions/getWebsiteSession.ts b/src/queries/analytics/sessions/getWebsiteSession.ts
|index f9b9f39a..e3d6eada 100644
|--- a/src/queries/analytics/sessions/getWebsiteSession.ts
|+++ b/src/queries/analytics/sessions/getWebsiteSession.ts
--------------------------
No file to patch.  Skipping patch.
2 out of 2 hunks ignored
(Stripping trailing CRs from patch; use --binary to disable.)
can't find file to patch at input line 1409
Perhaps you should have used the -p or --strip option?
The text leading up to this was:
--------------------------
|diff --git a/src/queries/analytics/sessions/getWebsiteSessions.ts b/src/queries/analytics/sessions/getWebsiteSessions.ts
|index d2a827d0..88a08166 100644
|--- a/src/queries/analytics/sessions/getWebsiteSessions.ts
|+++ b/src/queries/analytics/sessions/getWebsiteSessions.ts
--------------------------
No file to patch.  Skipping patch.
2 out of 2 hunks ignored
(Stripping trailing CRs from patch; use --binary to disable.)
can't find file to patch at input line 1437
Perhaps you should have used the -p or --strip option?
The text leading up to this was:
--------------------------
|diff --git a/src/queries/analytics/sessions/saveSessionData.ts b/src/queries/analytics/sessions/saveSessionData.ts
|index f9f0276e..cf2292e1 100644
|--- a/src/queries/analytics/sessions/saveSessionData.ts
|+++ b/src/queries/analytics/sessions/saveSessionData.ts
--------------------------
No file to patch.  Skipping patch.
1 out of 1 hunk ignored
(Stripping trailing CRs from patch; use --binary to disable.)
can't find file to patch at input line 1450
Perhaps you should have used the -p or --strip option?
The text leading up to this was:
--------------------------
|diff --git a/src/queries/prisma/team.ts b/src/queries/prisma/team.ts
|index e516c446..908eec14 100644
|--- a/src/queries/prisma/team.ts
|+++ b/src/queries/prisma/team.ts
--------------------------
No file to patch.  Skipping patch.
2 out of 2 hunks ignored
(Stripping trailing CRs from patch; use --binary to disable.)
can't find file to patch at input line 1475
Perhaps you should have used the -p or --strip option?
The text leading up to this was:
--------------------------
|diff --git a/src/queries/prisma/user.ts b/src/queries/prisma/user.ts
|index 9b471787..0ca79502 100644
|--- a/src/queries/prisma/user.ts
|+++ b/src/queries/prisma/user.ts
--------------------------
No file to patch.  Skipping patch.
1 out of 1 hunk ignored
(Stripping trailing CRs from patch; use --binary to disable.)
can't find file to patch at input line 1496
Perhaps you should have used the -p or --strip option?
The text leading up to this was:
--------------------------
|diff --git a/src/queries/prisma/website.ts b/src/queries/prisma/website.ts
|index 0814a137..2acdb182 100644
|--- a/src/queries/prisma/website.ts
|+++ b/src/queries/prisma/website.ts
--------------------------
No file to patch.  Skipping patch.
2 out of 2 hunks ignored
 i have error

**Comment by Maxime-J** [comment]
All these `No file to patch. Skipping patch.` indicates that it was patched from the wrong location.
Patch command has to be launched from Umami root folder, where there are the scripts and src folders.

**Comment by alphaleadership** [comment]
Is Work
